services:
  - type: web
    name: skinmarket
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        fromDatabase:
          name: skinmarket-db
          property: connectionString
      - key: STEAM_API_KEY
        sync: false
      - key: STEAM_BOT_ENABLED
        value: "true"
      - key: STEAM_BOT_USERNAME
        sync: false
      - key: STEAM_BOT_PASSWORD
        sync: false
      - key: STEAM_BOT_STEAM_ID
        sync: false
      - key: STEAM_BOT_TRADE_URL
        sync: false
      - key: STEAM_BOT_SHARED_SECRET
        sync: false
      - key: STEAM_BOT_IDENTITY_SECRET
        sync: false

databases:
  - name: skinmarket-db
    plan: starter
